"""End-to-end tests driving sync() against libraries generated by jellyplex-gen.

These are the only tests that exercise the full pipeline
(`guess_library_type` → `scan_media_library` → `process_movie` → summary).
The unit tests cover each stage; this covers their composition.

When Paket 1 (translation engine extraction) and Paket 4 (materializer DI,
sync-everything default) land, these tests are the first to fail if the
pipeline assembly silently breaks.
"""

from pathlib import Path

import pytest

import jellyplex_sync as jp
from jellyplex_sync.sync import guess_library_type
from jellyplex_gen import (
    CuratedTitleSource,
    FlatLibraryStructure,
    PlexNamingConvention,
    build_manifest,
    materialize,
)


def _generate_plex_lib(root: Path, seed: str = "e2e-001", movies: int = 6) -> jp.MediaLibrary:
    manifest = build_manifest(seed=seed, movie_count=movies, title_source=CuratedTitleSource())
    materialize(
        manifest,
        root,
        naming=PlexNamingConvention(),
        structure=FlatLibraryStructure(),
    )
    return manifest


@pytest.fixture
def plex_source(tmp_path: Path) -> tuple[Path, object]:
    src = tmp_path / "plex"
    src.mkdir()
    manifest = _generate_plex_lib(src)
    return src, manifest


def test_end_to_end_plex_to_jellyfin_produces_target(plex_source, tmp_path: Path):
    src, manifest = plex_source
    dst = tmp_path / "jellyfin"
    dst.mkdir()

    rc = jp.sync(str(src), str(dst))
    assert rc == 0

    source_movie_dirs = sorted(p.name for p in src.iterdir() if p.is_dir())
    target_movie_dirs = sorted(p.name for p in dst.iterdir() if p.is_dir())
    assert len(target_movie_dirs) == len(source_movie_dirs), (
        f"Movie count mismatch: source={len(source_movie_dirs)}, target={len(target_movie_dirs)}"
    )
    assert len(target_movie_dirs) == len(manifest.movies)


def test_end_to_end_videos_are_hardlinked_to_source(plex_source, tmp_path: Path):
    src, _ = plex_source
    dst = tmp_path / "jellyfin"
    dst.mkdir()

    rc = jp.sync(str(src), str(dst))
    assert rc == 0

    source_videos = list(src.rglob("*.mkv"))
    target_videos = list(dst.rglob("*.mkv"))
    assert source_videos, "generator produced no .mkv files"
    assert len(target_videos) == len(source_videos)

    target_by_size = {v.stat().st_size: v for v in target_videos}
    for sv in source_videos:
        tv = target_by_size.get(sv.stat().st_size)
        assert tv is not None, f"no target video matching size of {sv.name}"
        # Same inode = real hardlink, not a copy. If a future change accidentally
        # turns this into a copy, this assertion catches it.
        assert sv.samefile(tv) or any(sv.samefile(t) for t in target_videos), (
            f"source video {sv.name} not hardlinked to any target"
        )


def test_end_to_end_is_idempotent(plex_source, tmp_path: Path):
    src, _ = plex_source
    dst = tmp_path / "jellyfin"
    dst.mkdir()

    assert jp.sync(str(src), str(dst)) == 0
    snapshot = sorted(p.relative_to(dst).as_posix() for p in dst.rglob("*"))
    assert jp.sync(str(src), str(dst)) == 0
    snapshot2 = sorted(p.relative_to(dst).as_posix() for p in dst.rglob("*"))
    assert snapshot == snapshot2, "second sync changed the target tree"


def test_end_to_end_auto_detects_plex_source(plex_source, tmp_path: Path):
    """The generated library has `{imdb-tt...}` markers, which guess_library_type
    treats as a hard Plex signal."""
    src, _ = plex_source
    dst = tmp_path / "jellyfin"
    dst.mkdir()

    detected = guess_library_type(src)
    assert detected is jp.PlexLibrary
